// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shortsvc.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The create request creates a short key for a value.
type CreateRequest struct {
	V                    string   `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea5b1d546d95581e, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

// The create response contains the created key.
type CreateReply struct {
	K                    string   `protobuf:"bytes,1,opt,name=k,proto3" json:"k,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReply) Reset()         { *m = CreateReply{} }
func (m *CreateReply) String() string { return proto.CompactTextString(m) }
func (*CreateReply) ProtoMessage()    {}
func (*CreateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea5b1d546d95581e, []int{1}
}

func (m *CreateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReply.Unmarshal(m, b)
}
func (m *CreateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReply.Marshal(b, m, deterministic)
}
func (m *CreateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReply.Merge(m, src)
}
func (m *CreateReply) XXX_Size() int {
	return xxx_messageInfo_CreateReply.Size(m)
}
func (m *CreateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReply proto.InternalMessageInfo

func (m *CreateReply) GetK() string {
	if m != nil {
		return m.K
	}
	return ""
}

func (m *CreateReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// The Lookup request contains the key.
type LookupRequest struct {
	K                    string   `protobuf:"bytes,1,opt,name=k,proto3" json:"k,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupRequest) Reset()         { *m = LookupRequest{} }
func (m *LookupRequest) String() string { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()    {}
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea5b1d546d95581e, []int{2}
}

func (m *LookupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupRequest.Unmarshal(m, b)
}
func (m *LookupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupRequest.Marshal(b, m, deterministic)
}
func (m *LookupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupRequest.Merge(m, src)
}
func (m *LookupRequest) XXX_Size() int {
	return xxx_messageInfo_LookupRequest.Size(m)
}
func (m *LookupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupRequest proto.InternalMessageInfo

func (m *LookupRequest) GetK() string {
	if m != nil {
		return m.K
	}
	return ""
}

// The Lookup response contains the result of the lookup.
type LookupReply struct {
	V                    string   `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupReply) Reset()         { *m = LookupReply{} }
func (m *LookupReply) String() string { return proto.CompactTextString(m) }
func (*LookupReply) ProtoMessage()    {}
func (*LookupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea5b1d546d95581e, []int{3}
}

func (m *LookupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupReply.Unmarshal(m, b)
}
func (m *LookupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupReply.Marshal(b, m, deterministic)
}
func (m *LookupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupReply.Merge(m, src)
}
func (m *LookupReply) XXX_Size() int {
	return xxx_messageInfo_LookupReply.Size(m)
}
func (m *LookupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupReply.DiscardUnknown(m)
}

var xxx_messageInfo_LookupReply proto.InternalMessageInfo

func (m *LookupReply) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *LookupReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "pb.CreateRequest")
	proto.RegisterType((*CreateReply)(nil), "pb.CreateReply")
	proto.RegisterType((*LookupRequest)(nil), "pb.LookupRequest")
	proto.RegisterType((*LookupReply)(nil), "pb.LookupReply")
}

func init() { proto.RegisterFile("shortsvc.proto", fileDescriptor_ea5b1d546d95581e) }

var fileDescriptor_ea5b1d546d95581e = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xce, 0xc8, 0x2f,
	0x2a, 0x29, 0x2e, 0x4b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92,
	0xe5, 0xe2, 0x75, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0xe2, 0xe1, 0x62, 0x2c, 0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x2c, 0x53, 0xd2, 0xe5,
	0xe2, 0x86, 0x49, 0x17, 0xe4, 0x54, 0x82, 0x24, 0xb3, 0x61, 0x92, 0xd9, 0x42, 0x02, 0x5c, 0xcc,
	0xa9, 0x45, 0x45, 0x12, 0x4c, 0x60, 0x3e, 0x88, 0x09, 0x32, 0xcd, 0x27, 0x3f, 0x3f, 0xbb, 0xb4,
	0x00, 0xc9, 0x34, 0x84, 0x06, 0x90, 0x69, 0x30, 0x69, 0xa8, 0x69, 0x08, 0xab, 0x30, 0x4d, 0x33,
	0xca, 0xe4, 0x62, 0x0f, 0x06, 0xb9, 0x38, 0x35, 0x4f, 0x48, 0x8f, 0x8b, 0x0d, 0xe2, 0x0e, 0x21,
	0x41, 0xbd, 0x82, 0x24, 0x3d, 0x14, 0x27, 0x4b, 0xf1, 0x23, 0x0b, 0x15, 0xe4, 0x54, 0x2a, 0x31,
	0x80, 0xd4, 0x43, 0x6c, 0x82, 0xa8, 0x47, 0x71, 0x14, 0x44, 0x3d, 0x92, 0x43, 0x94, 0x18, 0x92,
	0xd8, 0xc0, 0x21, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x4c, 0x73, 0x38, 0x23, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShortenClient is the client API for Shorten service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShortenClient interface {
	// Creates a short key for a value.
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
	// Looks up a value by its key
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupReply, error)
}

type shortenClient struct {
	cc *grpc.ClientConn
}

func NewShortenClient(cc *grpc.ClientConn) ShortenClient {
	return &shortenClient{cc}
}

func (c *shortenClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := c.cc.Invoke(ctx, "/pb.Shorten/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupReply, error) {
	out := new(LookupReply)
	err := c.cc.Invoke(ctx, "/pb.Shorten/Lookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenServer is the server API for Shorten service.
type ShortenServer interface {
	// Creates a short key for a value.
	Create(context.Context, *CreateRequest) (*CreateReply, error)
	// Looks up a value by its key
	Lookup(context.Context, *LookupRequest) (*LookupReply, error)
}

func RegisterShortenServer(s *grpc.Server, srv ShortenServer) {
	s.RegisterService(&_Shorten_serviceDesc, srv)
}

func _Shorten_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Shorten/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shorten_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Shorten/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shorten_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Shorten",
	HandlerType: (*ShortenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Shorten_Create_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _Shorten_Lookup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shortsvc.proto",
}
